### ISSUE TITLE
ROUTING WON'T WORK

### ISSUE THREAD

**Issue by easa** [socialbahr/Wholeproject#14]
Routes won't work expect `home`.

There's the response:

```
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>Error</title>
    </head>
    <body>
        <pre>Cannot POST /login</pre>
    </body>
</html>
```

@ahmadbakhshi

**Comment by ahmadbakhshi** [comment]
pull from frepository and check the address to be "localhost:3000/api/login"
looks fine to me

**Comment by ahmadbakhshi** [comment]
![image](https://user-images.githubusercontent.com/17783744/56471477-5c559600-6468-11e9-8265-33282ea56164.png)

**Comment by easa** [comment]
It should work on develop branch!
Does it work then?
@ahmadbakhshi

**Comment by ahmadbakhshi** [comment]
it does,check the adress "localhost:3000/api/login"
