### ISSUE TITLE
unit test

### ISSUE THREAD

**Issue by ahmadbakhshi** [socialbahr/Wholeproject#3]
add unit test to everything

**Comment by easa** [comment]
Please write unit tests.
@ahmadbakhshi

**Comment by easa** [comment]
Please study [write-better-conditionals](https://scotch.io/bar-talk/5-tips-to-write-better-conditionals-in-javascript) about how to pass parameter to write effective functions, [javascript-arguments](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/arguments#Examples) about what it is and [jQuery-plugin-prameter](https://stackoverflow.com/a/17130247) to see how we used to pass options in jQuery plagin. thanks.
